package option

const (
	OPTION_PULL_REQUEST_REVIEW_WAIT_COUNT = 1
	OPTION_TEAM_REVIEW_LOAD = 2
	OPTION_INVITE_MEMBERS = 3
	OPTION_MILESTONE_ITEMS = 4
	OPTION_MILESTONE_PROGRESS = 5
	OPTION_SCHEDULER = 6
)

type Option struct {
	Id   int32
	Name string
	Deprecated bool
}

