name: Go Build

on: [push]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - name: Download modules
        run: go mod download
      - name: Build API
        run: go build ./cmd/api
